### ISSUE TITLE
The Robotarm Take No Reaction after Following the Step in "Visualizing MoveIt in RViz" 

### ISSUE THREAD

**Issue by Sgt-Harry** [ros-planning/moveit2_tutorials#502]
### Description
I was following the step in Visualizing MoveIt in RViz. Everything seems good before the second click of the next botton. Rviz gives me the info that it has successfully planed the path. But when I try to press it again to execute the plan, it just have no reaction. I had the same problem on VM before, when I was thinking it might be the issue of VM. But it still happened after I changed my platform to WSL2. 

### Your environment
* ROS Distro: [Humble]
* OS Version: e.g. Ubuntu 22.04
* Source build
* source build by ''git clone https://github.com/ros-planning/moveit2_tutorials -b main --depth 1''

### Steps to reproduce
I followd the step in tutorial,. 

### Expected behaviour
The Robotarm in Rviz should execute the plan and draw a line.

### Backtrace or Console output
output by hello_moveit
```
harry@LAPTOP-9979S1EP:~/ws_moveit2$ ros2 run hello_moveit hello_moveit
[INFO] [1662024801.002254457] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.180845 seconds
[INFO] [1662024801.002593745] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[WARN] [1662024801.049706096] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!
[INFO] [1662024801.076990685] [move_group_interface]: Ready to take commands for planning group panda_arm.
[INFO] [1662024801.080549867] [hello_moveit.remote_control]: RemoteControl Ready.
[INFO] [1662024801.080855020] [hello_moveit.remote_control]: Waiting to continue: Press 'Next' in the RvizVisualToolsGui window to plan
[INFO] [1662024858.834484878] [hello_moveit.remote_control]: ... continuing
[INFO] [1662024858.837432860] [move_group_interface]: MoveGroup action client/server ready
```
output by rviz
```harry@LAPTOP-9979S1EP:~/ws_moveit2$ ros2 launch moveit2_tutorials demo.launch.py
[INFO] [launch]: All log files can be found below /home/harry/.ros/log/2022-09-01-17-26-35-984776-LAPTOP-9979S1EP-18608
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [18609]
[INFO] [static_transform_publisher-2]: process started with pid [18611]
[INFO] [robot_state_publisher-3]: process started with pid [18613]
[INFO] [move_group-4]: process started with pid [18615]
[INFO] [ros2_control_node-5]: process started with pid [18617]
[INFO] [spawner-6]: process started with pid [18619]
[INFO] [spawner-7]: process started with pid [18621]
[INFO] [spawner-8]: process started with pid [18623]
[static_transform_publisher-2] [WARN] [1662024396.408955800] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-2] [INFO] [1662024396.434717335] [static_transform_publisher]: Spinning until stopped - publishing transform
[static_transform_publisher-2] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-2] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-2] from 'world' to 'panda_link0'
[robot_state_publisher-3] Link panda_link1 had 1 children
[robot_state_publisher-3] Link panda_link2 had 1 children
[robot_state_publisher-3] Link panda_link3 had 1 children
[robot_state_publisher-3] Link panda_link4 had 1 children
[robot_state_publisher-3] Link panda_link5 had 1 children
[robot_state_publisher-3] Link panda_link6 had 1 children
[robot_state_publisher-3] Link panda_link7 had 1 children
[robot_state_publisher-3] Link panda_link8 had 1 children
[robot_state_publisher-3] Link panda_hand had 2 children
[robot_state_publisher-3] Link panda_leftfinger had 0 children
[robot_state_publisher-3] Link panda_rightfinger had 0 children
[robot_state_publisher-3] [INFO] [1662024396.446044875] [robot_state_publisher]: got segment panda_hand
[robot_state_publisher-3] [INFO] [1662024396.446240232] [robot_state_publisher]: got segment panda_leftfinger
[robot_state_publisher-3] [INFO] [1662024396.446258396] [robot_state_publisher]: got segment panda_link0
[robot_state_publisher-3] [INFO] [1662024396.446263816] [robot_state_publisher]: got segment panda_link1
[robot_state_publisher-3] [INFO] [1662024396.446267784] [robot_state_publisher]: got segment panda_link2
[robot_state_publisher-3] [INFO] [1662024396.446271551] [robot_state_publisher]: got segment panda_link3
[robot_state_publisher-3] [INFO] [1662024396.446275088] [robot_state_publisher]: got segment panda_link4
[robot_state_publisher-3] [INFO] [1662024396.446278694] [robot_state_publisher]: got segment panda_link5
[robot_state_publisher-3] [INFO] [1662024396.446282451] [robot_state_publisher]: got segment panda_link6
[robot_state_publisher-3] [INFO] [1662024396.446286168] [robot_state_publisher]: got segment panda_link7
[robot_state_publisher-3] [INFO] [1662024396.446289905] [robot_state_publisher]: got segment panda_link8
[robot_state_publisher-3] [INFO] [1662024396.446293592] [robot_state_publisher]: got segment panda_rightfinger
[ros2_control_node-5] [INFO] [1662024396.457092476] [resource_manager]: Loading hardware 'PandaFakeSystem' 
[ros2_control_node-5] [INFO] [1662024396.459162297] [resource_manager]: Initialize hardware 'PandaFakeSystem' 
[ros2_control_node-5] [WARN] [1662024396.459701942] [mock_generic_system]: Parsing of optional initial interface values failed or uses a deprecated format. Add initial values for every state interface in the ros2_control.xacro. For example: 
[ros2_control_node-5] <state_interface name="velocity"> 
[ros2_control_node-5]   <param name="initial_value">0.0</param> 
[ros2_control_node-5] </state_interface>
[ros2_control_node-5] [INFO] [1662024396.459765792] [resource_manager]: Successful initialization of hardware 'PandaFakeSystem'
[ros2_control_node-5] [INFO] [1662024396.460299375] [resource_manager]: Loading hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1662024396.460442805] [resource_manager]: Initialize hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1662024396.460578139] [resource_manager]: Successful initialization of hardware 'PandaHandFakeSystem'
[ros2_control_node-5] [INFO] [1662024396.460856923] [resource_manager]: 'configure' hardware 'PandaFakeSystem' 
[ros2_control_node-5] [INFO] [1662024396.460893983] [resource_manager]: Successful 'configure' of hardware 'PandaFakeSystem'
[ros2_control_node-5] [INFO] [1662024396.460920212] [resource_manager]: 'activate' hardware 'PandaFakeSystem' 
[ros2_control_node-5] [INFO] [1662024396.460925903] [resource_manager]: Successful 'activate' of hardware 'PandaFakeSystem'
[ros2_control_node-5] [INFO] [1662024396.460932966] [resource_manager]: 'configure' hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1662024396.460936283] [resource_manager]: Successful 'configure' of hardware 'PandaHandFakeSystem'
[ros2_control_node-5] [INFO] [1662024396.460944518] [resource_manager]: 'activate' hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1662024396.460947874] [resource_manager]: Successful 'activate' of hardware 'PandaHandFakeSystem'
[ros2_control_node-5] [INFO] [1662024396.484570453] [controller_manager]: update rate is 100 Hz
[ros2_control_node-5] [INFO] [1662024396.485081095] [controller_manager]: RT kernel is recommended for better performance
[move_group-4] [INFO] [1662024396.544948841] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00822242 seconds
[move_group-4] [INFO] [1662024396.545511919] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[move_group-4] Link panda_link1 had 1 children
[move_group-4] Link panda_link2 had 1 children
[move_group-4] Link panda_link3 had 1 children
[move_group-4] Link panda_link4 had 1 children
[move_group-4] Link panda_link5 had 1 children
[move_group-4] Link panda_link6 had 1 children
[move_group-4] Link panda_link7 had 1 children
[move_group-4] Link panda_link8 had 1 children
[move_group-4] Link panda_hand had 2 children
[move_group-4] Link panda_leftfinger had 0 children
[move_group-4] Link panda_rightfinger had 0 children
[ros2_control_node-5] [INFO] [1662024396.747013564] [controller_manager]: Loading controller 'panda_arm_controller'
[spawner-8] [INFO] [1662024396.763472343] [spawner_panda_hand_controller]: Waiting for '/controller_manager' node to exist
[ros2_control_node-5] [INFO] [1662024396.771473701] [joint_trajectory_controller.interpolation_methods]: No interpolation method parameter was given. Using the default, VARIABLE_DEGREE_SPLINE.
[ros2_control_node-5] [INFO] [1662024396.776243246] [controller_manager]: Loading controller 'joint_state_broadcaster'
[move_group-4] [INFO] [1662024396.782934605] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-4] [INFO] [1662024396.784889390] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
[spawner-7] [INFO] [1662024396.789795077] [spawner_panda_arm_controller]: Loaded panda_arm_controller
[move_group-4] [INFO] [1662024396.795291358] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-4] [INFO] [1662024396.798745423] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-4] [INFO] [1662024396.798855671] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[move_group-4] [INFO] [1662024396.801876059] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-4] [INFO] [1662024396.801979243] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-4] [INFO] [1662024396.804997265] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
[ros2_control_node-5] [INFO] [1662024396.806363187] [controller_manager]: Configuring controller 'panda_arm_controller'
[ros2_control_node-5] [INFO] [1662024396.806806701] [panda_arm_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[move_group-4] [INFO] [1662024396.807988270] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-4] [WARN] [1662024396.809139184] [moveit.ros.occupancy_map_monitor.middleware_handle]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-4] [ERROR] [1662024396.809223212] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
[ros2_control_node-5] [INFO] [1662024396.809970229] [panda_arm_controller]: Controller state will be published at 50.00 Hz.
[ros2_control_node-5] [INFO] [1662024396.813786019] [panda_arm_controller]: Action status changes will be monitored at 20.00 Hz.
[move_group-4] [INFO] [1662024396.815543079] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'ompl'
[spawner-6] [INFO] [1662024396.819055861] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ros2_control_node-5] [INFO] [1662024396.824498884] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-5] [INFO] [1662024396.824716343] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[spawner-7] [INFO] [1662024396.847007056] [spawner_panda_arm_controller]: Configured and activated panda_arm_controller
[move_group-4] [INFO] [1662024396.857050480] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
[move_group-4] [INFO] [1662024396.862729607] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.path_tolerance' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1662024396.862801593] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.resample_dt' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1662024396.862807454] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.min_angle_change' was not set. Using default value: 0.001000
[move_group-4] [INFO] [1662024396.862945784] [moveit_ros.fix_workspace_bounds]: Param 'ompl.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-4] [INFO] [1662024396.862973466] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_bounds_error' was set to 0.100000
[move_group-4] [INFO] [1662024396.862978596] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1662024396.863000968] [moveit_ros.fix_start_state_collision]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1662024396.863005416] [moveit_ros.fix_start_state_collision]: Param 'ompl.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-4] [INFO] [1662024396.863044469] [moveit_ros.fix_start_state_collision]: Param 'ompl.max_sampling_attempts' was not set. Using default value: 100
[move_group-4] [INFO] [1662024396.863110924] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[move_group-4] [INFO] [1662024396.863136292] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Resolve constraint frames to robot links'
[move_group-4] [INFO] [1662024396.863139989] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-4] [INFO] [1662024396.863143446] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-4] [INFO] [1662024396.863146281] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-4] [INFO] [1662024396.863149547] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[spawner-6] [INFO] [1662024396.867509913] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[ros2_control_node-5] [INFO] [1662024396.975071691] [controller_manager]: Loading controller 'panda_hand_controller'
[spawner-8] [INFO] [1662024397.007202186] [spawner_panda_hand_controller]: Loaded panda_hand_controller
[ros2_control_node-5] [INFO] [1662024397.010077831] [controller_manager]: Configuring controller 'panda_hand_controller'
[ros2_control_node-5] [INFO] [1662024397.010343491] [panda_hand_controller]: Action status changes will be monitored at 20Hz.
[move_group-4] [INFO] [1662024397.012460569] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for panda_arm_controller
[move_group-4] [INFO] [1662024397.013229286] [moveit.plugins.moveit_simple_controller_manager]: Max effort set to 0.0
[move_group-4] [INFO] [1662024397.023631665] [moveit.plugins.moveit_simple_controller_manager]: Added GripperCommand controller for panda_hand_controller
[move_group-4] [INFO] [1662024397.024814349] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-4] [INFO] [1662024397.025626245] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[spawner-8] [INFO] [1662024397.027539375] [spawner_panda_hand_controller]: Configured and activated panda_hand_controller
[move_group-4] [INFO] [1662024397.029323847] [moveit_ros.trajectory_execution_manager]: Trajectory execution is managing controllers
[move_group-4] [INFO] [1662024397.029448702] [move_group.move_group]: MoveGroup debug mode is ON
[INFO] [spawner-7]: process has finished cleanly [pid 18621]
[INFO] [spawner-6]: process has finished cleanly [pid 18619]
[move_group-4] [INFO] [1662024397.092917726] [move_group.move_group]: 
[move_group-4] 
[move_group-4] ********************************************************
[move_group-4] * MoveGroup using: 
[move_group-4] *     - ApplyPlanningSceneService
[move_group-4] *     - ClearOctomapService
[move_group-4] *     - CartesianPathService
[move_group-4] *     - ExecuteTrajectoryAction
[move_group-4] *     - GetPlanningSceneService
[move_group-4] *     - KinematicsService
[move_group-4] *     - MoveAction
[move_group-4] *     - MotionPlanService
[move_group-4] *     - QueryPlannersService
[move_group-4] *     - StateValidationService
[move_group-4] ********************************************************
[move_group-4] 
[move_group-4] [INFO] [1662024397.093078198] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[move_group-4] [INFO] [1662024397.093092665] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context initialization complete
[move_group-4] Loading 'move_group/ApplyPlanningSceneService'...
[move_group-4] Loading 'move_group/ClearOctomapService'...
[move_group-4] Loading 'move_group/MoveGroupCartesianPathService'...
[move_group-4] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
[move_group-4] Loading 'move_group/MoveGroupGetPlanningSceneService'...
[move_group-4] Loading 'move_group/MoveGroupKinematicsService'...
[move_group-4] Loading 'move_group/MoveGroupMoveAction'...
[move_group-4] Loading 'move_group/MoveGroupPlanService'...
[move_group-4] Loading 'move_group/MoveGroupQueryPlannersService'...
[move_group-4] Loading 'move_group/MoveGroupStateValidationService'...
[move_group-4] 
[move_group-4] You can start planning now!
[move_group-4] 
[INFO] [spawner-8]: process has finished cleanly [pid 18623]
[rviz2-1] [INFO] [1662024399.698645424] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1662024399.698940328] [rviz2]: OpenGl version: 3.3 (GLSL 3.3)
[rviz2-1] [INFO] [1662024399.735156472] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-1]          at line 253 in /opt/ros/humble/include/class_loader/class_loader/class_loader_core.hpp
[rviz2-1] [ERROR] [1662024403.147469666] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-1] [INFO] [1662024403.180177115] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0040041 seconds
[rviz2-1] [INFO] [1662024403.180495344] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-1] [INFO] [1662024404.048165231] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00175269 seconds
[rviz2-1] [INFO] [1662024404.048605649] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-1] Link panda_link1 had 1 children
[rviz2-1] Link panda_link2 had 1 children
[rviz2-1] Link panda_link3 had 1 children
[rviz2-1] Link panda_link4 had 1 children
[rviz2-1] Link panda_link5 had 1 children
[rviz2-1] Link panda_link6 had 1 children
[rviz2-1] Link panda_link7 had 1 children
[rviz2-1] Link panda_link8 had 1 children
[rviz2-1] Link panda_hand had 2 children
[rviz2-1] Link panda_leftfinger had 0 children
[rviz2-1] Link panda_rightfinger had 0 children
[rviz2-1] [INFO] [1662024404.232507799] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-1] [INFO] [1662024404.236281714] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[static_transform_publisher-2] [INFO] [1662024413.571191942] [rclcpp]: signal_handler(signum=2)
[ros2_control_node-5] [INFO] [1662024413.571141761] [rclcpp]: signal_handler(signum=2)
[robot_state_publisher-3] [INFO] [1662024413.571190136] [rclcpp]: signal_handler(signum=2)
[ERROR] [robot_state_publisher-3]: process has died [pid 18613, exit code -11, cmd '/opt/ros/humble/lib/robot_state_publisher/robot_state_publisher --ros-args -r __node:=robot_state_publisher --params-file /tmp/launch_params_g401zmpa'].
[move_group-4] [INFO] [1662024413.571192600] [rclcpp]: signal_handler(signum=2)
[rviz2-1] [INFO] [1662024413.571258596] [rclcpp]: signal_handler(signum=2)
[move_group-4] [INFO] [1662024413.610248856] [moveit.ros_planning_interface.moveit_cpp]: Deleting MoveItCpp
[move_group-4] [INFO] [1662024413.613902843] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Stopped publishing maintained planning scene.
[rviz2-1] [INFO] [1662024413.616983099] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Stopping planning scene monitor
[move_group-4] [INFO] [1662024413.619430707] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Stopping world geometry monitor
[move_group-4] [INFO] [1662024413.620660303] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Stopping planning scene monitor
[move_group-4] Warning: class_loader.ClassLoader: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
[move_group-4]          at line 127 in ./src/class_loader.cpp
[INFO] [static_transform_publisher-2]: process has finished cleanly [pid 18611]
[INFO] [ros2_control_node-5]: process has finished cleanly [pid 18617]
[INFO] [move_group-4]: process has finished cleanly [pid 18615]
[move_group-4] 
[INFO] [rviz2-1]: process has finished cleanly [pid 18609]
harry@LAPTOP-9979S1EP:~/ws_moveit2$ source install/setup.bash
harry@LAPTOP-9979S1EP:~/ws_moveit2$ ros2 launch moveit2_tutorials demo.launch.py
[INFO] [launch]: All log files can be found below /home/harry/.ros/log/2022-09-01-17-32-42-768838-LAPTOP-9979S1EP-19284
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [19285]
[INFO] [static_transform_publisher-2]: process started with pid [19287]
[INFO] [robot_state_publisher-3]: process started with pid [19289]
[INFO] [move_group-4]: process started with pid [19291]
[INFO] [ros2_control_node-5]: process started with pid [19293]
[INFO] [spawner-6]: process started with pid [19295]
[INFO] [spawner-7]: process started with pid [19297]
[INFO] [spawner-8]: process started with pid [19299]
[static_transform_publisher-2] [WARN] [1662024763.196551251] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-2] [INFO] [1662024763.224874331] [static_transform_publisher]: Spinning until stopped - publishing transform
[static_transform_publisher-2] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-2] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-2] from 'world' to 'panda_link0'
[robot_state_publisher-3] Link panda_link1 had 1 children
[robot_state_publisher-3] Link panda_link2 had 1 children
[robot_state_publisher-3] Link panda_link3 had 1 children
[robot_state_publisher-3] Link panda_link4 had 1 children
[robot_state_publisher-3] Link panda_link5 had 1 children
[robot_state_publisher-3] Link panda_link6 had 1 children
[robot_state_publisher-3] Link panda_link7 had 1 children
[robot_state_publisher-3] Link panda_link8 had 1 children
[robot_state_publisher-3] Link panda_hand had 2 children
[robot_state_publisher-3] Link panda_leftfinger had 0 children
[robot_state_publisher-3] Link panda_rightfinger had 0 children
[robot_state_publisher-3] [INFO] [1662024763.235976358] [robot_state_publisher]: got segment panda_hand
[robot_state_publisher-3] [INFO] [1662024763.236242559] [robot_state_publisher]: got segment panda_leftfinger
[robot_state_publisher-3] [INFO] [1662024763.236263789] [robot_state_publisher]: got segment panda_link0
[robot_state_publisher-3] [INFO] [1662024763.236269499] [robot_state_publisher]: got segment panda_link1
[robot_state_publisher-3] [INFO] [1662024763.236274609] [robot_state_publisher]: got segment panda_link2
[robot_state_publisher-3] [INFO] [1662024763.236279077] [robot_state_publisher]: got segment panda_link3
[robot_state_publisher-3] [INFO] [1662024763.236283526] [robot_state_publisher]: got segment panda_link4
[robot_state_publisher-3] [INFO] [1662024763.236288074] [robot_state_publisher]: got segment panda_link5
[robot_state_publisher-3] [INFO] [1662024763.236292503] [robot_state_publisher]: got segment panda_link6
[robot_state_publisher-3] [INFO] [1662024763.236297071] [robot_state_publisher]: got segment panda_link7
[robot_state_publisher-3] [INFO] [1662024763.236301550] [robot_state_publisher]: got segment panda_link8
[robot_state_publisher-3] [INFO] [1662024763.236305888] [robot_state_publisher]: got segment panda_rightfinger
[ros2_control_node-5] [INFO] [1662024763.248831464] [resource_manager]: Loading hardware 'PandaFakeSystem' 
[ros2_control_node-5] [INFO] [1662024763.250824050] [resource_manager]: Initialize hardware 'PandaFakeSystem' 
[ros2_control_node-5] [WARN] [1662024763.251249290] [mock_generic_system]: Parsing of optional initial interface values failed or uses a deprecated format. Add initial values for every state interface in the ros2_control.xacro. For example: 
[ros2_control_node-5] <state_interface name="velocity"> 
[ros2_control_node-5]   <param name="initial_value">0.0</param> 
[ros2_control_node-5] </state_interface>
[ros2_control_node-5] [INFO] [1662024763.251311436] [resource_manager]: Successful initialization of hardware 'PandaFakeSystem'
[ros2_control_node-5] [INFO] [1662024763.251886447] [resource_manager]: Loading hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1662024763.252052520] [resource_manager]: Initialize hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1662024763.252208453] [resource_manager]: Successful initialization of hardware 'PandaHandFakeSystem'
[ros2_control_node-5] [INFO] [1662024763.252480925] [resource_manager]: 'configure' hardware 'PandaFakeSystem' 
[ros2_control_node-5] [INFO] [1662024763.252582669] [resource_manager]: Successful 'configure' of hardware 'PandaFakeSystem'
[ros2_control_node-5] [INFO] [1662024763.252651479] [resource_manager]: 'activate' hardware 'PandaFakeSystem' 
[ros2_control_node-5] [INFO] [1662024763.252656859] [resource_manager]: Successful 'activate' of hardware 'PandaFakeSystem'
[ros2_control_node-5] [INFO] [1662024763.252670815] [resource_manager]: 'configure' hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1662024763.252674382] [resource_manager]: Successful 'configure' of hardware 'PandaHandFakeSystem'
[ros2_control_node-5] [INFO] [1662024763.252681535] [resource_manager]: 'activate' hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1662024763.252684831] [resource_manager]: Successful 'activate' of hardware 'PandaHandFakeSystem'
[ros2_control_node-5] [INFO] [1662024763.276344864] [controller_manager]: update rate is 100 Hz
[ros2_control_node-5] [INFO] [1662024763.277852087] [controller_manager]: RT kernel is recommended for better performance
[move_group-4] [INFO] [1662024763.345065278] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00814435 seconds
[move_group-4] [INFO] [1662024763.345731180] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[move_group-4] Link panda_link1 had 1 children
[move_group-4] Link panda_link2 had 1 children
[move_group-4] Link panda_link3 had 1 children
[move_group-4] Link panda_link4 had 1 children
[move_group-4] Link panda_link5 had 1 children
[move_group-4] Link panda_link6 had 1 children
[move_group-4] Link panda_link7 had 1 children
[move_group-4] Link panda_link8 had 1 children
[move_group-4] Link panda_hand had 2 children
[move_group-4] Link panda_leftfinger had 0 children
[move_group-4] Link panda_rightfinger had 0 children
[spawner-6] [INFO] [1662024763.549539588] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-8] [INFO] [1662024763.553814128] [spawner_panda_hand_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1662024763.559858512] [spawner_panda_arm_controller]: Waiting for '/controller_manager' node to exist
[move_group-4] [INFO] [1662024763.590243551] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-4] [INFO] [1662024763.591176766] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-4] [INFO] [1662024763.597226946] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-4] [INFO] [1662024763.599968390] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-4] [INFO] [1662024763.600046447] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[move_group-4] [INFO] [1662024763.602532020] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-4] [INFO] [1662024763.602616739] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-4] [INFO] [1662024763.605393189] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
[move_group-4] [INFO] [1662024763.608534074] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-4] [WARN] [1662024763.611154060] [moveit.ros.occupancy_map_monitor.middleware_handle]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-4] [ERROR] [1662024763.611271100] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
[move_group-4] [INFO] [1662024763.618757354] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'ompl'
[move_group-4] [INFO] [1662024763.652940691] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
[move_group-4] [INFO] [1662024763.658318369] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.path_tolerance' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1662024763.658391847] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.resample_dt' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1662024763.658399061] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.min_angle_change' was not set. Using default value: 0.001000
[move_group-4] [INFO] [1662024763.658555355] [moveit_ros.fix_workspace_bounds]: Param 'ompl.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-4] [INFO] [1662024763.658614706] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_bounds_error' was set to 0.100000
[move_group-4] [INFO] [1662024763.658626769] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1662024763.658660292] [moveit_ros.fix_start_state_collision]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1662024763.658667826] [moveit_ros.fix_start_state_collision]: Param 'ompl.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-4] [INFO] [1662024763.658725284] [moveit_ros.fix_start_state_collision]: Param 'ompl.max_sampling_attempts' was not set. Using default value: 100
[move_group-4] [INFO] [1662024763.658824461] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[move_group-4] [INFO] [1662024763.658859246] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Resolve constraint frames to robot links'
[move_group-4] [INFO] [1662024763.658863364] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-4] [INFO] [1662024763.658866780] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-4] [INFO] [1662024763.658869666] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-4] [INFO] [1662024763.658873002] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[ros2_control_node-5] [INFO] [1662024763.759213031] [controller_manager]: Loading controller 'joint_state_broadcaster'
[move_group-4] [INFO] [1662024763.777636364] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for panda_arm_controller
[move_group-4] [INFO] [1662024763.778140592] [moveit.plugins.moveit_simple_controller_manager]: Max effort set to 0.0
[move_group-4] [INFO] [1662024763.786835514] [moveit.plugins.moveit_simple_controller_manager]: Added GripperCommand controller for panda_hand_controller
[move_group-4] [INFO] [1662024763.788346615] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-4] [INFO] [1662024763.788702223] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[spawner-6] [INFO] [1662024763.789449746] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ros2_control_node-5] [INFO] [1662024763.792660549] [controller_manager]: Loading controller 'panda_hand_controller'
[move_group-4] [INFO] [1662024763.794148973] [moveit_ros.trajectory_execution_manager]: Trajectory execution is managing controllers
[move_group-4] [INFO] [1662024763.794274268] [move_group.move_group]: MoveGroup debug mode is ON
[ros2_control_node-5] [INFO] [1662024763.818857657] [controller_manager]: Loading controller 'panda_arm_controller'
[spawner-8] [INFO] [1662024763.820073957] [spawner_panda_hand_controller]: Loaded panda_hand_controller
[ros2_control_node-5] [INFO] [1662024763.842907197] [joint_trajectory_controller.interpolation_methods]: No interpolation method parameter was given. Using the default, VARIABLE_DEGREE_SPLINE.
[ros2_control_node-5] [INFO] [1662024763.849005642] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-5] [INFO] [1662024763.849296599] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[spawner-7] [INFO] [1662024763.849462699] [spawner_panda_arm_controller]: Loaded panda_arm_controller
[ros2_control_node-5] [INFO] [1662024763.856754070] [controller_manager]: Configuring controller 'panda_hand_controller'
[ros2_control_node-5] [INFO] [1662024763.857060637] [panda_hand_controller]: Action status changes will be monitored at 20Hz.
[ros2_control_node-5] [INFO] [1662024763.857818569] [controller_manager]: Configuring controller 'panda_arm_controller'
[ros2_control_node-5] [INFO] [1662024763.858215124] [panda_arm_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ros2_control_node-5] [INFO] [1662024763.861466921] [panda_arm_controller]: Controller state will be published at 50.00 Hz.
[move_group-4] [INFO] [1662024763.864644418] [move_group.move_group]: 
[move_group-4] 
[move_group-4] ********************************************************
[move_group-4] * MoveGroup using: 
[move_group-4] *     - ApplyPlanningSceneService
[move_group-4] *     - ClearOctomapService
[move_group-4] *     - CartesianPathService
[move_group-4] *     - ExecuteTrajectoryAction
[move_group-4] *     - GetPlanningSceneService
[move_group-4] *     - KinematicsService
[move_group-4] *     - MoveAction
[move_group-4] *     - MotionPlanService
[move_group-4] *     - QueryPlannersService
[move_group-4] *     - StateValidationService
[move_group-4] ********************************************************
[move_group-4] 
[move_group-4] [INFO] [1662024763.864820459] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[move_group-4] [INFO] [1662024763.864832732] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context initialization complete
[move_group-4] Loading 'move_group/ApplyPlanningSceneService'...
[move_group-4] Loading 'move_group/ClearOctomapService'...
[move_group-4] Loading 'move_group/MoveGroupCartesianPathService'...
[move_group-4] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
[move_group-4] Loading 'move_group/MoveGroupGetPlanningSceneService'...
[move_group-4] Loading 'move_group/MoveGroupKinematicsService'...
[move_group-4] Loading 'move_group/MoveGroupMoveAction'...
[move_group-4] Loading 'move_group/MoveGroupPlanService'...
[move_group-4] Loading 'move_group/MoveGroupQueryPlannersService'...
[move_group-4] Loading 'move_group/MoveGroupStateValidationService'...
[move_group-4] 
[move_group-4] You can start planning now!
[move_group-4] 
[ros2_control_node-5] [INFO] [1662024763.864857567] [panda_arm_controller]: Action status changes will be monitored at 20.00 Hz.
[spawner-6] [INFO] [1662024763.899158471] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[spawner-8] [INFO] [1662024763.929542576] [spawner_panda_hand_controller]: Configured and activated panda_hand_controller
[spawner-7] [INFO] [1662024763.949565807] [spawner_panda_arm_controller]: Configured and activated panda_arm_controller
[INFO] [spawner-6]: process has finished cleanly [pid 19295]
[INFO] [spawner-8]: process has finished cleanly [pid 19299]
[INFO] [spawner-7]: process has finished cleanly [pid 19297]
[rviz2-1] [INFO] [1662024766.542068058] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1662024766.542343626] [rviz2]: OpenGl version: 3.3 (GLSL 3.3)
[rviz2-1] [INFO] [1662024766.581842807] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-1]          at line 253 in /opt/ros/humble/include/class_loader/class_loader/class_loader_core.hpp
[rviz2-1] [ERROR] [1662024769.981290952] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-1] [INFO] [1662024770.010023246] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00440588 seconds
[rviz2-1] [INFO] [1662024770.010388282] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-1] [INFO] [1662024770.861619694] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00208266 seconds
[rviz2-1] [INFO] [1662024770.862268854] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-1] Link panda_link1 had 1 children
[rviz2-1] Link panda_link2 had 1 children
[rviz2-1] Link panda_link3 had 1 children
[rviz2-1] Link panda_link4 had 1 children
[rviz2-1] Link panda_link5 had 1 children
[rviz2-1] Link panda_link6 had 1 children
[rviz2-1] Link panda_link7 had 1 children
[rviz2-1] Link panda_link8 had 1 children
[rviz2-1] Link panda_hand had 2 children
[rviz2-1] Link panda_leftfinger had 0 children
[rviz2-1] Link panda_rightfinger had 0 children
[rviz2-1] [INFO] [1662024771.049420039] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-1] [INFO] [1662024771.052826383] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-1] [WARN] [1662024814.151630553] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[move_group-4] [INFO] [1662024858.839348751] [moveit_move_group_default_capabilities.move_action_capability]: Received request
[move_group-4] [INFO] [1662024858.840372104] [moveit_move_group_default_capabilities.move_action_capability]: executing..
[move_group-4] [INFO] [1662024858.849700370] [moveit_move_group_default_capabilities.move_action_capability]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[move_group-4] [INFO] [1662024858.866423706] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[move_group-4] [INFO] [1662024863.417919906] [moveit_move_group_default_capabilities.move_action_capability]: Motion plan was computed successfully.
[rviz2-1] [ERROR] [1662024863.433481851] [moveit_rviz_plugin_render_tools.trajectory_visualization]: No robot state or robot model loaded
[rviz2-1] [INFO] [1662024869.722811334] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Stopping planning scene monitor
[rviz2-1] [INFO] [1662024870.428624046] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00167537 seconds
[rviz2-1] [INFO] [1662024870.428757347] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-1] Link panda_link1 had 1 children
[rviz2-1] Link panda_link2 had 1 children
[rviz2-1] Link panda_link3 had 1 children
[rviz2-1] Link panda_link4 had 1 children
[rviz2-1] Link panda_link5 had 1 children
[rviz2-1] Link panda_link6 had 1 children
[rviz2-1] Link panda_link7 had 1 children
[rviz2-1] Link panda_link8 had 1 children
[rviz2-1] Link panda_hand had 2 children
[rviz2-1] Link panda_leftfinger had 0 children
[rviz2-1] Link panda_rightfinger had 0 children
[rviz2-1] [INFO] [1662024870.569116778] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-1] [INFO] [1662024870.570921652] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
```
the cpp file of hello_moveit
```
#include <thread>  // <---- add this to the set of includes at the top
#include <memory>

#include <rclcpp/rclcpp.hpp>
#include <moveit/move_group_interface/move_group_interface.h>
#include <moveit_visual_tools/moveit_visual_tools.h>


int main(int argc, char * argv[])
{
  // Initialize ROS and create the Node
  rclcpp::init(argc, argv);
  auto const node = std::make_shared<rclcpp::Node>(
    "hello_moveit",
    rclcpp::NodeOptions().automatically_declare_parameters_from_overrides(true)
  );

  // Create a ROS logger
  auto const logger = rclcpp::get_logger("hello_moveit");

  // We spin up a SingleThreadedExecutor so MoveItVisualTools interact with ROS
  rclcpp::executors::SingleThreadedExecutor executor;
  executor.add_node(node);
  auto spinner = std::thread([&executor]() { executor.spin(); });

// Create the MoveIt MoveGroup Interface
using moveit::planning_interface::MoveGroupInterface;
auto move_group_interface = MoveGroupInterface(node, "panda_arm");

// Construct and initialize MoveItVisualTools
auto moveit_visual_tools = moveit_visual_tools::MoveItVisualTools{
    node, "panda_link0", rviz_visual_tools::RVIZ_MARKER_TOPIC,
    move_group_interface.getRobotModel()};
moveit_visual_tools.deleteAllMarkers();
moveit_visual_tools.loadRemoteControl();

// Create a closures for visualization
auto const draw_title = [&moveit_visual_tools](auto text) {
  auto const text_pose = [] {
    auto msg = Eigen::Isometry3d::Identity();
    msg.translation().z() = 1.0;
    return msg;
  }();
  moveit_visual_tools.publishText(text_pose, text, rviz_visual_tools::WHITE,
                                  rviz_visual_tools::XLARGE);
};
auto const prompt = [&moveit_visual_tools](auto text) {
  moveit_visual_tools.prompt(text);
};
auto const draw_trajectory_tool_path =
    [&moveit_visual_tools,
     jmg = move_group_interface.getRobotModel()->getJointModelGroup(
         "panda_arm")](auto const trajectory) {
      moveit_visual_tools.publishTrajectoryLine(trajectory, jmg);
    };

// Set a target Pose
auto const target_pose = [] {
  geometry_msgs::msg::Pose msg;
  msg.orientation.w = 1.0;
  msg.position.x = 0.28;
  msg.position.y = -0.2;
  msg.position.z = 0.5;
  return msg;
}();
move_group_interface.setPoseTarget(target_pose);

// Create a plan to that target pose
prompt("Press 'Next' in the RvizVisualToolsGui window to plan");
draw_title("Planning");
moveit_visual_tools.trigger();
auto const [success, plan] = [&move_group_interface] {
  moveit::planning_interface::MoveGroupInterface::Plan msg;
  auto const ok = static_cast<bool>(move_group_interface.plan(msg));
  return std::make_pair(ok, msg);
}();

// Execute the plan
if (success) {
  draw_trajectory_tool_path(plan.trajectory_);
  moveit_visual_tools.trigger();
  prompt("Press 'Next' in the RvizVisualToolsGui window to execute");
  draw_title("Executing");
  moveit_visual_tools.trigger();
  move_group_interface.execute(plan);
} else {
  draw_title("Planning Failed!");
  moveit_visual_tools.trigger();
  RCLCPP_ERROR(logger, "Planing failed!");
}

  // Shutdown ROS
  rclcpp::shutdown();
  spinner.join();  // <--- Join the thread before exiting
  return 0;
}
```

**Comment by tylerjw** [comment]
Thank you for your bug report. I'll try to reproduce this myself and see if I can figure it out.

**Comment by AndyZe** [comment]
It's almost certainly this bug. Still.

https://github.com/ros-planning/moveit2/issues/1474

**Comment by tylerjw** [comment]
Can you try using CycloneDDS or following the advice in that issue?

**Comment by Sgt-Harry** [comment]
> Can you try using CycloneDDS or following the advice in that issue?

Yes! After I installed the CycloneDDS und moved the MGI initialization before SingleThreadedExecutor. It works perfecty!
It has solved the problem that bothered me for a long time. Really appreciate that.
Maybe we need some changes in the tutorial document.

**Comment by tylerjw** [comment]
@Sgt-Harry would you like to make a PR to add a note to the tutorials about this issue and what changes worked for addressing it for you?

**Comment by AndyZe** [comment]
How about we fix it? As posted in the maintainer notes from last meeting -- https://discourse.ros.org/t/moveit-maintainer-meeting-aug-25/27090/3

A dedicated callback group in moveit_visual_tools might do it

**Comment by tylerjw** [comment]
My understanding from that meeting was that this was fixed upstream in FastDDS but we are waiting on the sync to have the fix available.

**Comment by Sgt-Harry** [comment]
> @Sgt-Harry would you like to make a PR to add a note to the tutorials about this issue and what changes worked for addressing it for you?

I'm glad to do that!
Its kind of a honor for me actually.

**Comment by yangming517** [comment]
hello ,would you please describe carefully how you use CycloneDDS  to solve this problem? I'm a beginner  of ros2.Hope your reply,thanks

**Comment by yangming517** [comment]
I have installed CycloneDDS  by 'sudo apt install ros-humble-rmw-cyclonedds-cpp' ,and added 'export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp' into my /.bashrc,but it still don't work
